# Base Flow Matching configuration
training:
  method: "fm"  # "fm" 
  n_epochs: 5000
  batch_size: 2000
  learning_rate: 0.001
  save_interval: 1000
  device: "gpu:2"
  seed: 0

model:
  type: 'mlp' # 'mlp' or 'mlp_time_embedding' or ...
  input_dim: 2
  hidden_dim: 128
  num_layers: 4
  activation: "softplus"
  time_varying: true

method:
  # Flow Matching specific
  sigma: 0.1  # 0.0 for deterministic FM, >0 for CFM
  time_sampling: "uniform"  # "uniform" or "logit_normal"

data:
  source_type: "std_gaussian"
  target_type: "gaussian0"
  dim: 2  # For high-dimensional datasets

output:
  checkpoint_dir: "checkpoints/generative/"
  model_name: "fm_std_gaussian_to_gaussian0"