# Stochastic Interpolants configuration
training:
  method: "si"
  n_epochs: 5000
  batch_size: 2000
  learning_rate: 0.001
  save_interval: 1000
  device: "cpu"
  seed: 42

model:
  type: 'mlp'  # 'mlp' or 'mlp_time_embedding' or ...
  input_dim: 2
  hidden_dim: 128
  num_layers: 4
  activation: "softplus"
  time_varying: true

method:
  # Stochastic Interpolants specific
  interpolant_schedule: "linear"  # "linear", "trigonometric", "polynomial", "vp"
  schedule_params:
    sigma: 0.1
    power: 2.0  # For polynomial schedule
  time_sampling: "uniform"

data:
  source_type: "8gaussians"
  target_type: "moons"
  dim: 2

output:
  checkpoint_dir: "checkpoints/generative/"
  model_name: "si_8gaussians_to_moons"